# Generated by Django 2.0.8 on 2018-09-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
    ]
