# Generated by Django 2.0.8 on 2018-09-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_image_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
