# Generated by Django 2.0.8 on 2018-09-28 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180929_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
